spring:
  application:
    name: EDU-VIDEO
  servlet:
    # 最大上传单个文件大小：默认1M
    multipart.max-file-size: 1024MB
    # 最大置总上传的数据大小 ：默认10M
    multipart.max-request-size: 1024MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    appname: EDU-VIDEO
    prefer-ip-address: true
server:
  port: 8003
oss:
  accessKeyId: LTAI5tRz4K1qcNiygSS2i9nY
  accessKeySecret: GdRMAGUnMF5T7kpTQYjTG5D6otY7vM

#阿里云的 key 测试可用备份以下
#oss.accessKeyId=LTAI5tRz4K1qcNiygSS2i9nY
#oss.accessKeySecret=GdRMAGUnMF5T7kpTQYjTG5D6otY7vM